### ISSUE TITLE
Missing identifier code severity

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-logger#2]
The error "Is not recognized as a standards identifier." is currently given the severity INFO. In my opinion that is at minimum a WARN, if not an ERROR.

**Comment by andrew2net** [comment]
@opoudjis we need to fix it in the flavor relaton-* gem. Which gem sends the message?

UPD I found it, the message is from relaton-iso. Fixing it.

**Comment by andrew2net** [comment]
@opoudjis I think it is a WARN. It means an incorrect reference is provided, so the warn is issued to inform about the problem. But if you think it is a ERROR, we can make it an error.

**Comment by opoudjis** [comment]
Well, all I can say is, when I try and fetch "ISO 00a", the log tells me it's INFO, and it should be WARN. The same applies to any standards codes not found.

**Comment by andrew2net** [comment]
fixed in relaton-iso v1.19.1
